/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Project.View;

import javax.swing.JOptionPane;


/**
 *
 * @author UG-Moustafa
 */
public class information1 extends javax.swing.JFrame {

    /**
     * Creates new form information
     */
    public information1() {
        initComponents();
        this.setSize(1200, 670);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTextField36 = new javax.swing.JTextField();
        jSeparator46 = new javax.swing.JSeparator();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jSeparator47 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        info_hotel = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        jSeparator50 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator51 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel116 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        province_airport = new javax.swing.JPanel();
        jTextField38 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jSeparator52 = new javax.swing.JSeparator();
        jLabel119 = new javax.swing.JLabel();
        jSeparator53 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator54 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel123 = new javax.swing.JLabel();
        jSeparator55 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        province = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jLabel120 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel121 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        jLabel122 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        bookCar = new javax.swing.JPanel();
        jLabel126 = new javax.swing.JLabel();
        jSeparator57 = new javax.swing.JSeparator();
        jTextField41 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jSpinField1 = new com.toedter.components.JSpinField();
        jLabel129 = new javax.swing.JLabel();
        jTextField42 = new javax.swing.JTextField();
        jLabel130 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel131 = new javax.swing.JLabel();
        jSeparator59 = new javax.swing.JSeparator();
        jSeparator60 = new javax.swing.JSeparator();
        jTextField43 = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jSpinField2 = new com.toedter.components.JSpinField();
        jLabel134 = new javax.swing.JLabel();
        jTextField44 = new javax.swing.JTextField();
        jLabel135 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        addCar = new javax.swing.JPanel();
        jLabel125 = new javax.swing.JLabel();
        jSeparator56 = new javax.swing.JSeparator();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel58 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator48 = new javax.swing.JSeparator();
        jSeparator49 = new javax.swing.JSeparator();
        jLabel114 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Home1 = new javax.swing.JLabel();
        Home2 = new javax.swing.JLabel();
        Home3 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/moustafa.png"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sittings.png"))); // NOI18N
        jLabel12.setText("moustafa");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel13.setText("FCI-UG");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setForeground(new java.awt.Color(0, 51, 102));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Tunga", 0, 18)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jTextField36.setForeground(new java.awt.Color(51, 51, 51));
        jTextField36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jTextField36);
        jTextField36.setBounds(100, 110, 240, 30);

        jSeparator46.setBackground(new java.awt.Color(153, 0, 51));
        jSeparator46.setForeground(new java.awt.Color(153, 0, 0));
        jPanel3.add(jSeparator46);
        jSeparator46.setBounds(90, 70, 290, 2);

        jLabel110.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(153, 0, 0));
        jLabel110.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Earth.png"))); // NOI18N
        jLabel110.setText("Personlize Your Search About Country");
        jPanel3.add(jLabel110);
        jLabel110.setBounds(90, 17, 370, 50);

        jLabel111.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(51, 51, 51));
        jLabel111.setText("Country  Name");
        jPanel3.add(jLabel111);
        jLabel111.setBounds(100, 90, 130, 20);

        jSeparator47.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator47.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator47.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator47);
        jSeparator47.setBounds(70, 33, 10, 280);

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 51), 2));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Country Name", "Price Going", "Price Going & Back", "Price Going For Baby", "Price Going For Child", "Price Go & Back For Baby", "Price Go & Back For Child"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 324, 960, 190);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/World.PNG"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(420, 50, 540, 240);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/chart-line-24.png"))); // NOI18N
        jLabel2.setText("Statistics Country");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(100, 280, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/updateeee.png"))); // NOI18N
        jLabel3.setText("UPdate country");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(100, 200, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        jLabel4.setText("Delete Country");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(100, 240, 160, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addd.png"))); // NOI18N
        jLabel5.setText("Add country");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(100, 160, 150, 30);

        jTabbedPane1.addTab("     Info About Country     ", jPanel3);

        info_hotel.setBackground(new java.awt.Color(255, 255, 255));
        info_hotel.setLayout(null);

        jLabel113.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(153, 0, 0));
        jLabel113.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hotel icon.png"))); // NOI18N
        jLabel113.setText("Personlize Your Search About Hotel");
        info_hotel.add(jLabel113);
        jLabel113.setBounds(90, 17, 370, 50);

        jLabel115.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(51, 51, 51));
        jLabel115.setText("Country Name");
        info_hotel.add(jLabel115);
        jLabel115.setBounds(280, 90, 130, 20);

        jTextField37.setForeground(new java.awt.Color(51, 51, 51));
        jTextField37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        info_hotel.add(jTextField37);
        jTextField37.setBounds(100, 110, 170, 30);

        jSeparator50.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator50.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator50.setOrientation(javax.swing.SwingConstants.VERTICAL);
        info_hotel.add(jSeparator50);
        jSeparator50.setBounds(70, 33, 10, 290);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addd.png"))); // NOI18N
        jLabel6.setText("Add Hotel");
        info_hotel.add(jLabel6);
        jLabel6.setBounds(100, 160, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/updateeee.png"))); // NOI18N
        jLabel7.setText("UPdate Hotel");
        info_hotel.add(jLabel7);
        jLabel7.setBounds(100, 210, 130, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        jLabel8.setText("Delete Hotel");
        info_hotel.add(jLabel8);
        jLabel8.setBounds(100, 250, 160, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/chart-line-24.png"))); // NOI18N
        jLabel9.setText("Statistics Hotel");
        info_hotel.add(jLabel9);
        jLabel9.setBounds(100, 290, 150, 30);

        jSeparator51.setBackground(new java.awt.Color(153, 0, 51));
        jSeparator51.setForeground(new java.awt.Color(153, 0, 0));
        info_hotel.add(jSeparator51);
        jSeparator51.setBounds(90, 70, 350, 2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EGYPT", "ITALY", "ENGLAND", "Paris" }));
        jComboBox1.setBorder(null);
        info_hotel.add(jComboBox1);
        jComboBox1.setBounds(280, 110, 160, 30);

        jLabel116.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(51, 51, 51));
        jLabel116.setText("Hotel  Name");
        info_hotel.add(jLabel116);
        jLabel116.setBounds(100, 90, 130, 20);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Country Name", "Hotel Name", "Price In Night", "Phone", "Address"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        info_hotel.add(jScrollPane1);
        jScrollPane1.setBounds(10, 350, 970, 160);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/procvince.png"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        info_hotel.add(jLabel14);
        jLabel14.setBounds(560, 70, 404, 250);

        jTabbedPane1.addTab("Info About Hotel", info_hotel);

        province_airport.setBackground(new java.awt.Color(255, 255, 255));
        province_airport.setLayout(null);

        jTextField38.setForeground(new java.awt.Color(51, 51, 51));
        jTextField38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        province_airport.add(jTextField38);
        jTextField38.setBounds(100, 170, 190, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Borg el Arb", "Cairo", "peko", "teco" }));
        jComboBox2.setBorder(null);
        province_airport.add(jComboBox2);
        jComboBox2.setBounds(100, 240, 190, 30);

        jLabel117.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel117.setForeground(new java.awt.Color(51, 51, 51));
        jLabel117.setText("Provinces Airports ");
        province_airport.add(jLabel117);
        jLabel117.setBounds(100, 220, 180, 20);

        jLabel118.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(51, 51, 51));
        jLabel118.setText("Province Name ");
        province_airport.add(jLabel118);
        jLabel118.setBounds(100, 140, 130, 20);

        jSeparator52.setBackground(new java.awt.Color(153, 0, 51));
        jSeparator52.setForeground(new java.awt.Color(153, 0, 0));
        province_airport.add(jSeparator52);
        jSeparator52.setBounds(90, 80, 490, 10);

        jLabel119.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel119.setForeground(new java.awt.Color(153, 0, 0));
        jLabel119.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/prcvince.png"))); // NOI18N
        jLabel119.setText("Personlize Your Search About Provinces");
        province_airport.add(jLabel119);
        jLabel119.setBounds(90, 17, 440, 50);

        jSeparator53.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator53.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator53.setOrientation(javax.swing.SwingConstants.VERTICAL);
        province_airport.add(jSeparator53);
        jSeparator53.setBounds(340, 90, 0, 200);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 153));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addd.png"))); // NOI18N
        jLabel15.setText("Add Province Or Aairport ");
        province_airport.add(jLabel15);
        jLabel15.setBounds(380, 110, 250, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 153));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/updateeee.png"))); // NOI18N
        jLabel16.setText("UPdate  Province Or Aairport");
        province_airport.add(jLabel16);
        jLabel16.setBounds(380, 160, 240, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 153));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        jLabel20.setText("Delete Province Or Aairport");
        province_airport.add(jLabel20);
        jLabel20.setBounds(380, 200, 230, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 153));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/chart-line-24.png"))); // NOI18N
        jLabel21.setText("Statistics Province Or Aairport");
        province_airport.add(jLabel21);
        jLabel21.setBounds(380, 240, 250, 30);

        jSeparator54.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator54.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator54.setOrientation(javax.swing.SwingConstants.VERTICAL);
        province_airport.add(jSeparator54);
        jSeparator54.setBounds(70, 53, 2, 260);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 0, 0));
        jLabel34.setText("Note :");
        province_airport.add(jLabel34);
        jLabel34.setBounds(90, 100, 37, 20);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel35.setText("  Enter The country and select Airport");
        province_airport.add(jLabel35);
        jLabel35.setBounds(130, 100, 200, 20);

        jTabbedPane1.addTab("Info About Provinces", province_airport);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jPanel2.add(jTextField1);
        jTextField1.setBounds(420, 270, 230, 30);

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jPanel2.add(jTextField2);
        jTextField2.setBounds(420, 170, 230, 30);

        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jPanel2.add(jTextField3);
        jTextField3.setBounds(80, 260, 230, 30);

        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4);
        jTextField4.setBounds(80, 360, 230, 30);

        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jPanel2.add(jTextField5);
        jTextField5.setBounds(80, 170, 230, 30);

        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jPanel2.add(jTextField6);
        jTextField6.setBounds(80, 460, 230, 30);

        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jPanel2.add(jTextField7);
        jTextField7.setBounds(420, 360, 230, 30);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(80, 100, 216, 2);

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 0, 0));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addddd.png"))); // NOI18N
        jLabel22.setText("Country");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(86, 42, 210, 50);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/r.png"))); // NOI18N
        jLabel23.setText("Price Going For Baby :  ");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(420, 140, 170, 20);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/r.png"))); // NOI18N
        jLabel24.setText("Country Name :");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(80, 140, 130, 20);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/r.png"))); // NOI18N
        jLabel25.setText("Price For Going  :");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(80, 230, 130, 20);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/r.png"))); // NOI18N
        jLabel26.setText("Price For Going & Back : ");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(80, 330, 170, 20);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/r.png"))); // NOI18N
        jLabel27.setText("Price Going For Child  : ");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(80, 430, 170, 20);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/r.png"))); // NOI18N
        jLabel28.setText("Price Going & Back For  Baby");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(420, 330, 210, 20);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/r.png"))); // NOI18N
        jLabel29.setText("Price Going & Back For child : ");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(420, 240, 200, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/_cancel.png"))); // NOI18N
        jButton1.setText("Cancel");
        jPanel2.add(jButton1);
        jButton1.setBounds(550, 450, 110, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add (2).png"))); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(420, 450, 120, 40);

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("validate");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(620, 240, 70, 20);

        jLabel41.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 0, 0));
        jLabel41.setText("validate");
        jPanel2.add(jLabel41);
        jLabel41.setBounds(200, 140, 70, 20);

        jLabel42.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 0, 0));
        jLabel42.setText("validate");
        jPanel2.add(jLabel42);
        jLabel42.setBounds(210, 230, 70, 20);

        jLabel43.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 0, 0));
        jLabel43.setText("validate");
        jPanel2.add(jLabel43);
        jLabel43.setBounds(250, 330, 70, 20);

        jLabel44.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(204, 0, 0));
        jLabel44.setText("validate");
        jPanel2.add(jLabel44);
        jLabel44.setBounds(240, 430, 70, 20);

        jLabel45.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(204, 0, 0));
        jLabel45.setText("validate");
        jPanel2.add(jLabel45);
        jLabel45.setBounds(580, 140, 70, 20);

        jTabbedPane1.addTab("Add Country", jPanel2);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setForeground(new java.awt.Color(0, 102, 102));
        jPanel7.setLayout(null);

        jLabel123.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel123.setForeground(new java.awt.Color(153, 0, 0));
        jLabel123.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addddd.png"))); // NOI18N
        jLabel123.setText(" Hotel");
        jPanel7.add(jLabel123);
        jLabel123.setBounds(90, 30, 190, 50);

        jSeparator55.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator55.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(jSeparator55);
        jSeparator55.setBounds(90, 82, 210, 10);

        jLabel36.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_required.gif"))); // NOI18N
        jLabel36.setText("Hotel Address     : ");
        jPanel7.add(jLabel36);
        jLabel36.setBounds(100, 380, 160, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(jComboBox4);
        jComboBox4.setBounds(280, 120, 220, 30);

        jLabel37.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_required.gif"))); // NOI18N
        jLabel37.setText("Hotel Phone        : ");
        jPanel7.add(jLabel37);
        jLabel37.setBounds(100, 260, 160, 30);

        jLabel38.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_required.gif"))); // NOI18N
        jLabel38.setText("Hotel Name         :  ");
        jPanel7.add(jLabel38);
        jLabel38.setBounds(100, 190, 160, 30);

        jLabel39.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_required.gif"))); // NOI18N
        jLabel39.setText("Country Name     :  ");
        jPanel7.add(jLabel39);
        jLabel39.setBounds(100, 120, 160, 30);

        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel7.add(jTextField8);
        jTextField8.setBounds(280, 380, 220, 30);

        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel7.add(jTextField9);
        jTextField9.setBounds(280, 190, 220, 30);

        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel7.add(jTextField10);
        jTextField10.setBounds(280, 260, 220, 30);

        jLabel40.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_required.gif"))); // NOI18N
        jLabel40.setText("Price At Night     : ");
        jPanel7.add(jLabel40);
        jLabel40.setBounds(100, 320, 160, 30);

        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel7.add(jTextField11);
        jTextField11.setBounds(280, 320, 220, 30);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 102, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add (2).png"))); // NOI18N
        jButton7.setText("Add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7);
        jButton7.setBounds(140, 460, 140, 40);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/_cancel.png"))); // NOI18N
        jButton8.setText("Cancel");
        jPanel7.add(jButton8);
        jButton8.setBounds(340, 460, 160, 40);

        jTabbedPane1.addTab("Add Hotel", jPanel7);

        province.setBackground(new java.awt.Color(255, 255, 255));
        province.setLayout(null);

        jSeparator6.setBackground(new java.awt.Color(204, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(204, 0, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        province.add(jSeparator6);
        jSeparator6.setBounds(470, 100, 10, 370);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        province.add(jSeparator2);
        jSeparator2.setBounds(110, 130, 280, 2);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        province.add(jSeparator3);
        jSeparator3.setBounds(580, 120, 233, 2);

        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 204));
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Airport-Blue-2-icon.png"))); // NOI18N
        jLabel30.setText("Add Airport ");
        province.add(jLabel30);
        jLabel30.setBounds(580, 40, 230, 70);

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 0, 51));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/prcvince.png"))); // NOI18N
        jLabel31.setText("Add province ");
        province.add(jLabel31);
        jLabel31.setBounds(110, 50, 250, 50);

        jTextField39.setForeground(new java.awt.Color(51, 51, 51));
        jTextField39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        province.add(jTextField39);
        jTextField39.setBounds(590, 210, 240, 30);

        jLabel120.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel120.setForeground(new java.awt.Color(102, 0, 0));
        jLabel120.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_required.gif"))); // NOI18N
        jLabel120.setText("Airport  Name ");
        province.add(jLabel120);
        jLabel120.setBounds(590, 190, 210, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Borg el Arb", "Cairo", "peko", "teco" }));
        jComboBox3.setBorder(null);
        province.add(jComboBox3);
        jComboBox3.setBounds(590, 290, 240, 30);

        jLabel121.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel121.setForeground(new java.awt.Color(51, 51, 51));
        jLabel121.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_required.gif"))); // NOI18N
        jLabel121.setText("Provinces Name");
        province.add(jLabel121);
        jLabel121.setBounds(590, 270, 130, 20);

        jTextField40.setForeground(new java.awt.Color(51, 51, 51));
        jTextField40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        province.add(jTextField40);
        jTextField40.setBounds(110, 210, 240, 30);

        jLabel122.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel122.setForeground(new java.awt.Color(51, 51, 51));
        jLabel122.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_required.gif"))); // NOI18N
        jLabel122.setText("Province Name ");
        province.add(jLabel122);
        jLabel122.setBounds(110, 180, 210, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 102, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add (2).png"))); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        province.add(jButton3);
        jButton3.setBounds(590, 370, 120, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/_cancel.png"))); // NOI18N
        jButton4.setText("Cancel");
        province.add(jButton4);
        jButton4.setBounds(730, 370, 110, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 102, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add (2).png"))); // NOI18N
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        province.add(jButton5);
        jButton5.setBounds(110, 380, 120, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/_cancel.png"))); // NOI18N
        jButton6.setText("Cancel");
        province.add(jButton6);
        jButton6.setBounds(240, 380, 110, 40);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("Airport wil be added  automaticly in Province listl ");
        province.add(jLabel32);
        jLabel32.setBounds(110, 300, 280, 20);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 0, 0));
        jLabel33.setText("Note :");
        province.add(jLabel33);
        jLabel33.setBounds(110, 280, 40, 20);

        jTabbedPane1.addTab("Add Province & Airport", province);

        bookCar.setBackground(new java.awt.Color(255, 255, 255));
        bookCar.setLayout(null);

        jLabel126.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel126.setForeground(new java.awt.Color(153, 0, 0));
        jLabel126.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/need for sped.png"))); // NOI18N
        jLabel126.setText("Booking Car ");
        bookCar.add(jLabel126);
        jLabel126.setBounds(80, 7, 390, 80);

        jSeparator57.setBackground(new java.awt.Color(153, 0, 51));
        jSeparator57.setForeground(new java.awt.Color(153, 0, 0));
        bookCar.add(jSeparator57);
        jSeparator57.setBounds(80, 90, 350, 2);

        jTextField41.setForeground(new java.awt.Color(51, 51, 51));
        jTextField41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bookCar.add(jTextField41);
        jTextField41.setBounds(80, 390, 220, 30);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EGYPT", "ITALY", "ENGLAND", "Paris" }));
        jComboBox5.setBorder(null);
        bookCar.add(jComboBox5);
        jComboBox5.setBounds(80, 260, 220, 30);

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 51, 153));
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addd.png"))); // NOI18N
        jLabel50.setText("Add Car");
        bookCar.add(jLabel50);
        jLabel50.setBounds(450, 160, 150, 30);

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 51, 153));
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/updateeee.png"))); // NOI18N
        jLabel51.setText("UPdate Car");
        bookCar.add(jLabel51);
        jLabel51.setBounds(450, 210, 130, 30);

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 51, 153));
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        jLabel52.setText("Delete Car");
        bookCar.add(jLabel52);
        jLabel52.setBounds(450, 260, 160, 30);

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 153));
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/chart-line-24.png"))); // NOI18N
        jLabel53.setText("Statistics Car");
        bookCar.add(jLabel53);
        jLabel53.setBounds(450, 310, 150, 30);

        jLabel127.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel127.setForeground(new java.awt.Color(51, 51, 51));
        jLabel127.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_required.gif"))); // NOI18N
        jLabel127.setText("Ticket Number");
        bookCar.add(jLabel127);
        jLabel127.setBounds(80, 140, 130, 30);

        jLabel128.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel128.setForeground(new java.awt.Color(51, 51, 51));
        jLabel128.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_required.gif"))); // NOI18N
        jLabel128.setText("Num of Night :");
        bookCar.add(jLabel128);
        jLabel128.setBounds(80, 310, 100, 30);
        bookCar.add(jSpinField1);
        jSpinField1.setBounds(230, 310, 70, 30);

        jLabel129.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel129.setForeground(new java.awt.Color(51, 51, 51));
        jLabel129.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_required.gif"))); // NOI18N
        jLabel129.setText("Car Type");
        bookCar.add(jLabel129);
        jLabel129.setBounds(80, 230, 90, 30);

        jTextField42.setForeground(new java.awt.Color(51, 51, 51));
        jTextField42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bookCar.add(jTextField42);
        jTextField42.setBounds(80, 170, 220, 30);

        jLabel130.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel130.setForeground(new java.awt.Color(51, 51, 51));
        jLabel130.setText("Total Price  :");
        bookCar.add(jLabel130);
        jLabel130.setBounds(80, 360, 120, 20);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jLabel131.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel131.setForeground(new java.awt.Color(153, 0, 0));
        jLabel131.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/need for sped.png"))); // NOI18N
        jLabel131.setText("Booking Car ");
        jPanel6.add(jLabel131);
        jLabel131.setBounds(90, 7, 380, 80);

        jSeparator59.setBackground(new java.awt.Color(153, 0, 51));
        jSeparator59.setForeground(new java.awt.Color(153, 0, 0));
        jPanel6.add(jSeparator59);
        jSeparator59.setBounds(90, 100, 350, 2);

        jSeparator60.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator60.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator60.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel6.add(jSeparator60);
        jSeparator60.setBounds(60, 100, 10, 360);

        jTextField43.setForeground(new java.awt.Color(51, 51, 51));
        jTextField43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.add(jTextField43);
        jTextField43.setBounds(90, 390, 170, 30);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EGYPT", "ITALY", "ENGLAND", "Paris" }));
        jComboBox6.setBorder(null);
        jPanel6.add(jComboBox6);
        jComboBox6.setBounds(90, 230, 170, 30);

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 51, 153));
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addd.png"))); // NOI18N
        jLabel54.setText("Add Car");
        jPanel6.add(jLabel54);
        jLabel54.setBounds(600, 80, 150, 30);

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 51, 153));
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/updateeee.png"))); // NOI18N
        jLabel55.setText("UPdate Car");
        jPanel6.add(jLabel55);
        jLabel55.setBounds(670, 140, 130, 30);

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 51, 153));
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        jLabel56.setText("Delete Car");
        jPanel6.add(jLabel56);
        jLabel56.setBounds(650, 280, 160, 30);

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 153));
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/chart-line-24.png"))); // NOI18N
        jLabel57.setText("Statistics Car");
        jPanel6.add(jLabel57);
        jLabel57.setBounds(670, 340, 150, 30);

        jLabel132.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel132.setForeground(new java.awt.Color(51, 51, 51));
        jLabel132.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_required.gif"))); // NOI18N
        jLabel132.setText("Ticket Number");
        jPanel6.add(jLabel132);
        jLabel132.setBounds(90, 110, 130, 30);

        jLabel133.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel133.setForeground(new java.awt.Color(51, 51, 51));
        jLabel133.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_required.gif"))); // NOI18N
        jLabel133.setText("Num of Night :");
        jPanel6.add(jLabel133);
        jLabel133.setBounds(90, 300, 100, 30);
        jPanel6.add(jSpinField2);
        jSpinField2.setBounds(200, 300, 60, 30);

        jLabel134.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel134.setForeground(new java.awt.Color(51, 51, 51));
        jLabel134.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_required.gif"))); // NOI18N
        jLabel134.setText("Car Type");
        jPanel6.add(jLabel134);
        jLabel134.setBounds(90, 200, 90, 30);

        jTextField44.setForeground(new java.awt.Color(51, 51, 51));
        jTextField44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.add(jTextField44);
        jTextField44.setBounds(90, 140, 170, 30);

        jLabel135.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel135.setForeground(new java.awt.Color(51, 51, 51));
        jLabel135.setText("Total Price");
        jPanel6.add(jLabel135);
        jLabel135.setBounds(90, 360, 120, 20);

        bookCar.add(jPanel6);
        jPanel6.setBounds(0, 0, 0, 0);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(102, 0, 0));
        jButton11.setText("Save booking");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        bookCar.add(jButton11);
        jButton11.setBounds(80, 450, 120, 40);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/_cancel.png"))); // NOI18N
        jButton12.setText("Cancel");
        bookCar.add(jButton12);
        jButton12.setBounds(210, 450, 100, 40);

        jPanel8.setBackground(new java.awt.Color(0, 204, 204));
        jPanel8.setPreferredSize(new java.awt.Dimension(5, 370));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        bookCar.add(jPanel8);
        jPanel8.setBounds(420, 150, 5, 340);

        jPanel9.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        bookCar.add(jPanel9);
        jPanel9.setBounds(50, 150, 5, 340);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/booking carrr.jpg"))); // NOI18N
        jLabel59.setToolTipText("");
        bookCar.add(jLabel59);
        jLabel59.setBounds(600, 120, 250, 230);

        jTabbedPane1.addTab("Bookin Car", bookCar);

        addCar.setBackground(new java.awt.Color(255, 255, 255));
        addCar.setLayout(null);

        jLabel125.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel125.setForeground(new java.awt.Color(153, 0, 0));
        jLabel125.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addddd.png"))); // NOI18N
        jLabel125.setText("Add New Car");
        addCar.add(jLabel125);
        jLabel125.setBounds(70, 20, 330, 60);

        jSeparator56.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator56.setForeground(new java.awt.Color(0, 0, 0));
        addCar.add(jSeparator56);
        jSeparator56.setBounds(70, 80, 300, 10);

        jLabel46.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(204, 0, 0));
        jLabel46.setText("validate");
        addCar.add(jLabel46);
        jLabel46.setBounds(190, 250, 70, 20);

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 51, 51));
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/r.png"))); // NOI18N
        jLabel47.setText("Car Type");
        addCar.add(jLabel47);
        jLabel47.setBounds(70, 150, 90, 30);

        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        addCar.add(jTextField12);
        jTextField12.setBounds(70, 280, 230, 30);

        jLabel48.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(204, 0, 0));
        jLabel48.setText("validate");
        addCar.add(jLabel48);
        jLabel48.setBounds(160, 150, 70, 30);

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 51, 51));
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/r.png"))); // NOI18N
        jLabel49.setText("Price Par Day");
        addCar.add(jLabel49);
        jLabel49.setBounds(70, 250, 110, 20);

        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        addCar.add(jTextField13);
        jTextField13.setBounds(70, 180, 230, 30);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 102, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add (2).png"))); // NOI18N
        jButton9.setText("Add");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        addCar.add(jButton9);
        jButton9.setBounds(70, 340, 110, 40);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/_cancel.png"))); // NOI18N
        jButton10.setText("Cancel");
        addCar.add(jButton10);
        jButton10.setBounds(200, 340, 100, 40);

        jSeparator4.setBackground(new java.awt.Color(153, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(153, 0, 51));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        addCar.add(jSeparator4);
        jSeparator4.setBounds(410, 150, 50, 240);

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hand write car.jpg"))); // NOI18N
        addCar.add(jLabel58);
        jLabel58.setBounds(440, 90, 390, 300);

        jTabbedPane1.addTab("Add Car", addCar);

        jTabbedPane1.setSelectedComponent(jPanel3);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 103, 1200, 530);

        jSeparator5.setBackground(new java.awt.Color(0, 102, 153));
        jSeparator5.setForeground(new java.awt.Color(0, 102, 204));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(828, 10, 2, 90);

        jSeparator48.setBackground(new java.awt.Color(0, 102, 153));
        jSeparator48.setForeground(new java.awt.Color(0, 102, 204));
        jSeparator48.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator48);
        jSeparator48.setBounds(950, 10, 2, 90);

        jSeparator49.setBackground(new java.awt.Color(0, 153, 204));
        jSeparator49.setForeground(new java.awt.Color(0, 102, 153));
        jSeparator49.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator49);
        jSeparator49.setBounds(1070, 10, 2, 90);

        jLabel114.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hotel.png"))); // NOI18N
        jLabel114.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel114MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel114);
        jLabel114.setBounds(980, 10, 56, 70);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/p.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel19);
        jLabel19.setBounds(1090, 10, 64, 60);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/h.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(740, 10, 64, 60);

        Home.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Home.setForeground(new java.awt.Color(153, 0, 0));
        Home.setText("Booking Ticket");
        jPanel1.add(Home);
        Home.setBounds(850, 74, 90, 20);

        Home1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Home1.setForeground(new java.awt.Color(153, 0, 0));
        Home1.setText("Booking hotel");
        jPanel1.add(Home1);
        Home1.setBounds(970, 70, 90, 30);

        Home2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Home2.setForeground(new java.awt.Color(153, 0, 0));
        Home2.setText("Overview");
        jPanel1.add(Home2);
        Home2.setBounds(750, 74, 60, 20);

        Home3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Home3.setForeground(new java.awt.Color(153, 0, 0));
        Home3.setText("Passanger");
        jPanel1.add(Home3);
        Home3.setBounds(1090, 70, 70, 30);

        jLabel124.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tickets-icon.png"))); // NOI18N
        jLabel124.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel124MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel124);
        jLabel124.setBounds(860, 24, 60, 50);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logo 2.png"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 10, 150, 90);

        jLabel112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/booking bg.png"))); // NOI18N
        jPanel1.add(jLabel112);
        jLabel112.setBounds(0, 0, 1200, 630);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1197, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.setVisible(false);
        Overview2 ov = new Overview2();
        ov.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        this.setVisible(false);
        Search_passanger s = new Search_passanger();
        s.setVisible(true);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel114MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel114MouseClicked
        this.setVisible(false);
        Booking_Tickt bk = new Booking_Tickt();
        bk.setVisible(true);
    }//GEN-LAST:event_jLabel114MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Project.Model.model model_set = new Project.Model.model();
        model_set.set_country_name(jTextField5.getText());
        model_set.set_price_on_go_pass(Integer.parseInt(jTextField3.getText()));
        model_set.set_p_on_go_back_pass(Integer.parseInt(jTextField4.getText()));
        model_set.set_price_on_go_childern(Integer.parseInt(jTextField6.getText()));
        model_set.set_price_on_go_baby(Integer.parseInt(jTextField2.getText()));
        model_set.set_p_on_go_back_childern(Integer.parseInt(jTextField1.getText()));
        model_set.set_p_on_go_back_baby(Integer.parseInt(jTextField7.getText()));

        Project.Controller.Orders o = new Project.Controller.Orders();
        o.inset_into_country(model_set);
        JOptionPane.showMessageDialog(null, "A New Country Has benn Add Successfully ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Project.Model.model model_set_hotel = new Project.Model.model();
        model_set_hotel.set_country_id(1);
        model_set_hotel.set_hotel_name(jTextField9.getText());
        model_set_hotel.set_phone(Integer.parseInt(jTextField10.getText()));
        model_set_hotel.set_price_at_night(Integer.parseInt(jTextField11.getText()));
        model_set_hotel.set_address(jTextField8.getText());
         
        Project.Controller.Orders o =new Project.Controller.Orders();
        
         o.isert_into_hotel(model_set_hotel);
         JOptionPane.showMessageDialog(null, "A New Hotel  Has benn Add Successfully ");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel124MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel124MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel124MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(information1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(information1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(information1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(information1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new information1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Home1;
    private javax.swing.JLabel Home2;
    private javax.swing.JLabel Home3;
    public javax.swing.JPanel addCar;
    public javax.swing.JPanel bookCar;
    public javax.swing.JPanel info_hotel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JSeparator jSeparator47;
    private javax.swing.JSeparator jSeparator48;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator50;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator52;
    private javax.swing.JSeparator jSeparator53;
    private javax.swing.JSeparator jSeparator54;
    private javax.swing.JSeparator jSeparator55;
    private javax.swing.JSeparator jSeparator56;
    private javax.swing.JSeparator jSeparator57;
    private javax.swing.JSeparator jSeparator59;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator60;
    private com.toedter.components.JSpinField jSpinField1;
    private com.toedter.components.JSpinField jSpinField2;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    public javax.swing.JPanel province;
    public javax.swing.JPanel province_airport;
    // End of variables declaration//GEN-END:variables
}
